### ISSUE TITLE
Input/Output image size

### ISSUE THREAD

**Issue by faxioman** [crockwell/pixelsynth#2]
Hi, I’m impressed with the result using also some old b/w photos.
I’m wondering if could be possible to use and render images bigger than 256x256.
Great work!

**Comment by crockwell** [comment]
Hey - appreciate the kind words! 

So the code is currently setup to preprocess larger images of arbitrary size and then work at 256x256 resolution. 

Rendering images at higher than 256x256 would take some work, and would involve making a few adaptations to the code and probably retraining. I think you may be able to get good results at higher resolution with much less effort by simply taking the outputs of the network and using a pretrained super resolution model to increase resolution e.g. [EDSR](https://github.com/sanghyun-son/EDSR-PyTorch#quickstart-demo) or [SRGAN](https://github.com/tensorlayer/srgan).
